# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
allspice = Spice.create({name: "Allspice", image: "http://i.ebayimg.com/00/s/ODAwWDgwMA==/z/FVYAAOSwofxUjwiw/$_57.JPG", description: "Also called Pimento or Jamaican Pepper. Dried, nearly ripe berries from the Jamaican Myrtle tree; sweet and savory flavor. Smells and tastes like a combination of Nutmeg, Cinnamon, and Cloves. Available whole and ground.", hint: "A key ingredient in “jerk” seasoning but also added to pickling spice mixtures, mincemeat, pot roast and stews, sausage and cured meats, ham, gravies, ketchup, poultry marinades, and fish"})
anise = Spice.create({name: "Anise", image: "http://www.educatedpalate.com/GlossaryItem/9b79608e-5d9d-4da7-acf6-e53adddc184e.jpg", description: "ANISE or ANISEED is an aromatic spice that imparts a distinct flavor of licorice and is commonly used to make the liqueurs ouzo, anisette, and pernod. Anise is used in cookies and cakes, and a sprinkling of the seeds adds an unusual twist to fruit salads, particularly those utilizing citrus fruits.", hint: "It is an aromatic spice that imparts a distinct flavor of licorice. It is also popular world wide as an ingredient in liqueurs and candies."})
basil = Spice.create({name: "Basil", image: "http://www.offthegridnews.com/wp-content/uploads/2011/04/Basil.jpg", description: "BASIL is one of the most relished of herbs and one that has an important place in herbal lore and legend, spanning many ages and cultures. In the summer, the intoxicating scent of fresh sweet basil fills produce markets, and its brief season should be fully enjoyed. Though basil makes an excellent dried herb whose sweet-and-spicy flavor is welcome in many dishes, the result is very different when using it fresh. Fresh basil is the main component of pesto sauces and has a special affinity with tomato-based pasta sauces and fresh tomato salads (as in the classic tomato, mozzarella, and basil salad). Dried basil is good in soups, marinades and vinaigrettes, grain dishes, herb breads, and omelets. It may also be used to flavor tomato sauces when fresh basil is unavailable.", hint: "It's an essential ingrdient in many Italian dishes"})
bayleaf = Spice.create({name: "Bay Leaf", image: "http://gpwgroups.com/wp-content/uploads/2015/01/bay-leaves-photo.jpg", description: "Bay Leaves are the whole, dried leaves of the bay laurel tree and are most useful in long-simmering recipes, such as soups and stews, where their flavor has a chance to permeate. Its warm, somewhat “woodsy” character lends itself especially well to recipes that contain tomatoes, beans, corn, and potatoes.", hint: "These aromatic, woodsy-tasting leaves are typically sold dried."})

cardamom = Spice.create({name: "Cardamom", image: "https://photographicdictionary.com/sites/photographicdictionary.com/files/photos/c/cardamom.jpg", description: "Cardamom, derived from a plant native to India, is available in whole or ground form. Bought whole, the seed pods must be opened, revealing several small, dark seeds. These aromatic seeds have a flavor that is hard to describe, but is appropriate for both sweet and savory dishes. The whole seeds lend an aromatic quality to grain dishes, especially fruit-and-nut grain pilafs as well as curries containing potatoes or peas.", hint: "Spice related to Ginger"})
chilli = Spice.create({name: "Chilli", image: "https://photographicdictionary.com/sites/photographicdictionary.com/files/photos/c/chili.jpg", description: "The chili pepper, also spelt chilli, is a small fruit that ranges in colour from green to yellow to red, the most common. The chili is very hot, and when you eat one it feels like your mouth is burning. Chilis are in the same family as the capsicum (bell pepper).", hint: "Things can get really hot with this one"})
cayene_pepper = Spice.create({name: "Cayene Pepper", image: "http://www.ecorazzi.com/wp-content/uploads/2012/10/cayenne-pepper.jpg", description: "CAYENNE PEPPER is perhaps the hottest of ground spices, ground and dried from a very hot variety of a pepper of the capsicum genus. A small amount goes a long way and is used to give fiery flavor to Mexican, Indian, and some Southeast Asian cuisines and is also useful in spicing Creole and Cajun specialties. Cayenne pepper lends itself to vegetable or bean stews, curries, chilies, spicy cold noodle dishes, and hot-and-sour dishes.", hint: "You will definitely need a fire brigade to burn out the fire in your mouth"})
chives = Spice.create({name: "Chives", image: "https://www.americanseedco.com/wp-content/uploads/2013/06/Chives.jpg", description: "Chives are a member of the onion family. Chives grow in clumps from a bulb under the ground. You can use the leaves cut up on salads or on potato or pasta dishes. You can use the flowers in salads too. Chives are very easy to grow from seed, and they can also grow new chives by digging up a clump and splitting off the smaller side bulbs. There are different varieties of chives, one of the most useful being garlic chives, which have leaves and flowers with a strong garlic flavour.", hint: "It's flavor is very much akin to that of scallions, yet more delicate"})
cilantro = Spice.create({name: "Cilantro", image: "http://spittoon.23andme.com/wp-content/uploads/2008/08/istock_000005991545xsmall.jpg", description: "CILANTRO is an herb that is never available in dried form, since its pungent flavor and aroma seem to dissipate almost entirely when dried. Sometimes referred to as Spanish or Chinese parsley, this is the same herb whose seeds are the spice coriander. It is used widely in Mexican, Indian and Asian cuisines. Cilantro adds an unusual zest to pinto bean stews, Spanish-style tomato sauces for enchiladas, tacos and the like, curried vegetable stews, and corn dishes such as corn-stuffed peppers.", hint: "Often times confused with coriander. Also called Chinese parsley"})
cinnamon = Spice.create({name: "Cinnamon", image: "http://authoritynutrition.com/wp-content/uploads/2014/12/cinnamon-sticks-and-powder-on-wooden-table.jpg", description: "Cinnamon is made from the bark of a small tree native to Sri Lanka. The smell and taste comes from an oil that the plant makes. Cinnamon is usually sold as a powder in shops, and is simply the bark of the tree ground into powder. Cinnamon is used in a lot of cooking, mostly in sweet desserts like chocolate dishes, apple pie and many cakes and cookies. Cinnamon is used with sugar on cinnamon donuts.", hint: " A sweet, aromatic spice"})
cloves = Spice.create({name: "Clove", image: "http://www.seriouseats.com/images/20110209-136748-cloves-post.jpg", description: "CLOVES are a pleasant, sweet spice like cinnamon, but have a stronger flavor and a sharp aroma. Whole cloves are the buds of the evergreen clove tree. Stewed fruits benefit from a handful of whole cloves while they are simmering, and fragrant pilafs are made even more so by addition of some whole cloves. You may leave the cloves in the dishes you are making, but you may not enjoy biting into one, since the flavor is somewhat bitter", hint: "These are great to suck on when your throat has given up on you"})
coriander = Spice.create({name: "Coriander", image: "http://ichef.bbci.co.uk/food/ic/food_16x9_608/foods/c/coriander_fresh_16x9.jpg", description: "The spice coriander is the seed portion of the Coriander plant, from which Cilantro is derived. It has a citrus-like flavor and tang.", hint: "Another name for cilantro"})
cumin = Spice.create({name: "Cumin", image: "", description: "", hint: ""})

















